# REFERENCE ARTIFACT — see infra-reference/README.md.
# This sketches the isolated Terraform root module the design doc (section 3d)
# calls for: its own state, scoped to nothing but the shared CMS WAF
# IPSet, so a whitelist commit's apply can never touch unrelated in-flight
# platform infra. It is not a complete, deployable module and is never
# applied by this repo or any process in src/.

terraform {
  required_version = ">= 1.5"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # section 3d: isolated state file, separate from the rest of the platform's
  # infra state, so this module's plan/apply is scoped to exactly the
  # resources below.
  backend "s3" {
    bucket = "REPLACE_ME-terraform-state"
    key    = "cms-whitelist/terraform.tfstate"
    region = "us-east-1"
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

# The source of truth: generated by the batching worker
# (src/whitelist/generators/whitelist-tfvars.generator.ts) and committed here
# by GitHubPublisher (section 3a step 4) as ip_whitelist.tfvars.json. Keyed by IP;
# the tenant/addedAt metadata rides along for traceability but Terraform only
# consumes the keys.
variable "cms_whitelist_ips" {
  type = map(object({
    tenant  = string
    addedAt = string
  }))
}

# NOTE: AWS WAFv2 IPSets are version-scoped — one IPSet holds either IPv4 or
# IPv6 addresses, never both. A complete module would split
# var.cms_whitelist_ips by address family and declare a second IPSet (plus a
# rule referencing both) for IPv6 entries; omitted here since this file is
# illustrative only.
resource "aws_wafv2_ip_set" "cms_whitelist" {
  name               = "cms-whitelist"
  scope              = "REGIONAL"
  ip_address_version = "IPV4"
  addresses          = keys(var.cms_whitelist_ips)
}
